/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACell: typeof import('ano-ui/components/ACell/ACell.vue')['default']
    ACellGroup: typeof import('ano-ui/components/ACellGroup/ACellGroup.vue')['default']
    ASwitch: typeof import('ano-ui/components/ASwitch/ASwitch.vue')['default']
    CourseActionSheet: typeof import('./src/components/timetable/CourseActionSheet.vue')['default']
    TimetableAction: typeof import('./src/components/timetable/TimetableAction.vue')['default']
    TimetableContent: typeof import('./src/components/timetable/TimetableContent.vue')['default']
    TimetableHeader: typeof import('./src/components/timetable/TimetableHeader.vue')['default']
    UBasePage: typeof import('./src/components/UnoUI/UBasePage/UBasePage.vue')['default']
    UButton: typeof import('./src/components/UnoUI/UButton/UButton.vue')['default']
    UCellGroup: typeof import('./src/components/mine/UCellGroup/UCellGroup.vue')['default']
    UCellItem: typeof import('./src/components/mine/UCellItem/UCellItem.vue')['default']
    UCollapse: typeof import('./src/components/score/UCollapse/UCollapse.vue')['default']
    UDrawerPage: typeof import('./src/components/UnoUI/UDrawerPage/UDrawerPage.vue')['default']
    UDropdown: typeof import('./src/components/UDropdown/UDropdown.vue')['default']
    UGridGroup: typeof import('./src/components/index/UGridGroup/UGridGroup.vue')['default']
    UGridItem: typeof import('./src/components/index/UGridItem/UGridItem.vue')['default']
    UMsg: typeof import('./src/components/UnoUI/UMsg/UMsg.vue')['default']
    UNotify: typeof import('./src/components/UnoUI/UNotify/UNotify.vue')['default']
    UResult: typeof import('./src/components/UnoUI/UResult/UResult.vue')['default']
    USwiper: typeof import('./src/components/index/USwiper/USwiper.vue')['default']
    UTab: typeof import('./src/components/UTab/UTab.vue')['default']
    UToast: typeof import('./src/components/UnoUI/UToast/UToast.vue')['default']
  }
}
